"""Uniswap Trading API tools.

Two tools for the uniswap specialist:

- `get_uniswap_quote`: read-only data tool. Calls Uniswap Trading API (/quote)
  to get real-time price quotes, routing, and gas estimates on Ethereum mainnet,
  Base, or Sepolia testnet.
- `build_uniswap_swap_tx`: action tool. Calls Uniswap Trading API (/quote then /swap)
  to retrieve real swap calldata generated by Uniswap (never hand-rolled).
  Prepends an ERC20 approve() step if token_in is an ERC20 token. Returns an
  unsigned transaction payload for the connected wallet to sign.
"""

import json
from decimal import Decimal, InvalidOperation
from typing import Any

import httpx
from langchain_core.tools import tool

from app.core.config import get_settings
from app.tools._evm_encoding import _encode_address, _encode_uint, network_name

APPROVE_SELECTOR = "095ea7b3"
NATIVE_ETH_ADDRESSES = {
    "0x0000000000000000000000000000000000000000",
    "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
}


async def _uniswap_post(path: str, payload: dict[str, Any]) -> Any:
    settings = get_settings()
    headers = {"Content-Type": "application/json"}
    if settings.uniswap_api_key:
        headers["x-api-key"] = settings.uniswap_api_key

    url = (
        path
        if path.startswith("http")
        else f"{settings.uniswap_api_base_url.rstrip('/')}/{path.lstrip('/')}"
    )
    async with httpx.AsyncClient(timeout=15) as client:
        resp = await client.post(url, json=payload, headers=headers)
        resp.raise_for_status()
        return resp.json()


@tool
async def get_uniswap_quote(
    token_in_address: str,
    token_out_address: str,
    amount_in: str | float,
    chain_id: int = 1,
    swapper_address: str | None = None,
    slippage_tolerance_bps: int = 50,
) -> str:
    """Fetch a real-time price quote from Uniswap Trading API on Ethereum mainnet, Base, or Sepolia.

    Calls POST /quote on Uniswap Trading API. `chain_id` is 1 for Ethereum mainnet, 8453 for Base,
    or 11155111 for Sepolia testnet.
    `token_in_address` and `token_out_address` are 0x EVM contract addresses (use 0x0000000000000000000000000000000000000000
    or 0xEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE for native ETH). `amount_in` is in raw token units or decimal amount string.
    Returns raw JSON string containing price quote, route details, and gas estimate."""
    payload = {
        "type": "exactIn",
        "amount": str(amount_in),
        "tokenIn": token_in_address,
        "tokenOut": token_out_address,
        "tokenInChainId": chain_id,
        "tokenOutChainId": chain_id,
        "swapper": swapper_address or "0x0000000000000000000000000000000000000000",
        "slippageTolerance": slippage_tolerance_bps / 10000.0,
    }
    try:
        quote_data = await _uniswap_post("/quote", payload)
        return json.dumps(quote_data)
    except Exception as exc:  # noqa: BLE001 - surface error string to LLM
        return json.dumps({"error": f"Failed to fetch Uniswap quote: {exc}"})


@tool
async def build_uniswap_swap_tx(
    token_in_address: str,
    token_out_address: str,
    amount_in: str | float,
    chain_id: int = 1,
    swapper_address: str = "0x0000000000000000000000000000000000000000",
    slippage_tolerance_bps: int = 50,
) -> str:
    """Build an unsigned Uniswap swap transaction via Uniswap Trading API for Ethereum mainnet, Base, or Sepolia.

    Calls POST /quote and POST /swap on Uniswap Trading API to retrieve real calldata generated by
    Uniswap. Never hand-encodes swap calldata. If token_in is an ERC20 token, prepends a classic approve()
    step. Returns an unsigned action payload JSON with transaction steps for the connected wallet to sign."""
    quote_payload = {
        "type": "exactIn",
        "amount": str(amount_in),
        "tokenIn": token_in_address,
        "tokenOut": token_out_address,
        "tokenInChainId": chain_id,
        "tokenOutChainId": chain_id,
        "swapper": swapper_address,
        "slippageTolerance": slippage_tolerance_bps / 10000.0,
    }

    try:
        quote_data = await _uniswap_post("/quote", quote_payload)
    except Exception as exc:  # noqa: BLE001
        return json.dumps({"error": f"Failed to get quote from Uniswap Trading API: {exc}"})

    swap_payload = {
        "quote": quote_data,
        "swapper": swapper_address,
        "slippageTolerance": slippage_tolerance_bps / 10000.0,
    }

    try:
        swap_data = await _uniswap_post("/swap", swap_payload)
    except Exception as exc:  # noqa: BLE001
        return json.dumps(
            {"error": f"Failed to generate swap calldata from Uniswap Trading API: {exc}"}
        )

    # Extract transaction fields from Uniswap Trading API response
    swap_obj = swap_data.get("swap") or swap_data.get("methodParameters") or swap_data
    to_address = swap_obj.get("to") or swap_obj.get("target") or ""
    calldata = swap_obj.get("data") or swap_obj.get("calldata") or "0x"
    value = swap_obj.get("value") or "0x0"
    if isinstance(value, int):
        value = hex(value)
    elif not str(value).startswith("0x"):
        try:
            value = hex(int(value))
        except (ValueError, TypeError):
            value = "0x0"

    network = network_name(chain_id)
    steps = []

    # Prepend ERC20 approve step if token_in is not native ETH
    is_native = token_in_address.lower() in NATIVE_ETH_ADDRESSES
    if not is_native and to_address:
        # amount_in is already in the token's raw smallest-unit representation
        # (matching what's sent to the /quote and /swap calls above), so it
        # must be parsed exactly — float() silently loses precision above
        # 2**53 and would approve the wrong amount for realistic on-chain
        # amounts (e.g. 1e18 wei).
        try:
            amount_wei = int(Decimal(str(amount_in)))
        except (InvalidOperation, ValueError, TypeError):
            amount_wei = 2**256 - 1
        try:
            approve_calldata = (
                "0x" + APPROVE_SELECTOR + _encode_address(to_address) + _encode_uint(amount_wei)
            )
        except ValueError as exc:
            return json.dumps({"error": str(exc)})
        steps.append(
            {
                "label": f"Approve {token_in_address} for Uniswap Router",
                "to": token_in_address,
                "data": approve_calldata,
                "value": "0x0",
            }
        )

    steps.append(
        {
            "label": f"Swap {amount_in} token via Uniswap on {network}",
            "to": to_address,
            "data": calldata,
            "value": str(value),
        }
    )

    return json.dumps(
        {
            "protocol": "Uniswap Trading API",
            "network": network,
            "chain_id": chain_id,
            "human_message": f"Swap {amount_in} on Uniswap ({network})",
            "steps": steps,
        }
    )


UNISWAP_TOOLS = [get_uniswap_quote, build_uniswap_swap_tx]
